### ISSUE TITLE
Migrate from travis to GitHub Actions

### ISSUE THREAD

**Issue by mkorszun** [meltwater/gen_rmq#100]

**Comment by vorce** [comment]
Github's own CI/CD might also be an option soon :)

**Comment by vorce** [comment]
I've tried the beta of github CI for an elixir project (https://github.com/vorce/lasso), so far I prefer Drone.

**Comment by mkorszun** [comment]
Cool, would love to hear your opinion and learning.

**Comment by akoutmos** [comment]
This issue has been open for a while. Is Drone still the preferred CI tool? If GitHub Actions is a viable alternative I would be willing to tackle this effort ;).

**Comment by mkorszun** [comment]
hey @akoutmos, I would say go for it. If you could also tackle plt caching it would be awesome.

**Comment by akoutmos** [comment]
Sounds good! I'll try to squeeze this in at some point this week as time allows :)

**Comment by mkorszun** [comment]
Released 🎉 Thanks @akoutmos for all the work!!!
