### ISSUE TITLE
Use handle_continue for non-blocking consumer/publisher setup

### ISSUE THREAD

**Issue by mkorszun** [meltwater/gen_rmq#108]
After bumping minimum required elixir version to 1.7 we are ready to use [handle_continue](https://hexdocs.pm/elixir/GenServer.html) callback:
https://medium.com/@tylerpachal/introduction-to-handle-continue-in-elixir-and-when-to-use-it-53ba5519cc17

**Comment by vorce** [comment]
Closing, it's not worth making the OTP version requirement change (see discussion in #111)
