### ISSUE TITLE
GenRMQ.Publisher top-level metadata fields are incorrectly merged

### ISSUE THREAD

**Issue by dch** [meltwater/gen_rmq#128]
`merge_metadata/2`should not override a custom `content_type`, or any other similar
mandatory parameter:

```elixir
> GenRMQ.Publisher.base_metadata([]) |> GenRMQ.Publisher.merge_metadata(content_type: "text/plain", some: "header")
[
  timestamp: 1573481570357,
  app_id: "gen_rmq",
  content_type: "application/json",
  headers: [some: "header"]
]
```

**Comment by mkorszun** [comment]
Happening here https://github.com/meltwater/gen_rmq/blob/master/lib/publisher.ex#L339

**Comment by mkorszun** [comment]
@dch fix is ready -> https://github.com/meltwater/gen_rmq/pull/129
