### ISSUE TITLE
Allow init to accept queue details 

### ISSUE THREAD

**Issue by themitigater** [meltwater/gen_rmq#130]
Hey,
I was wondering why we don't have an option to provide args to `start_link` during consumer setup instead of declaring a keyword list statically and using it? Is there a specific reason to not support this?

_Note: The amqp lib does supports this._

**Comment by mkorszun** [comment]
hey @themitigater, no specific reason. It started like this, because internally at Meltwater this was our initial approach. I agree, that there should be an option to specify params also via `start_link` function. We will try to prioritize it. Feel free to propose a PR as well.

**Comment by Shemeikka** [comment]
Does anyone have any preference on how this should be done?

For example. should init have queue_options that are basically same as [AMQP Queue declare's](https://hexdocs.pm/amqp/AMQP.Queue.html#declare/3) and are passed to the Queue.declare on setup_consumer.

And maybe combine that with the ability to specify all the init params via start_link function like suggested above?

**Comment by mkorszun** [comment]
@Shemeikka let's start first with a new param for an `init` callback.

**Comment by spier** [comment]
@themitigater and @Shemeikka. Thanks for contributing to this discussion! :)
Does either of you feel passionate enough about this particular issue to send a PR? i.e. would either of you need this feature for the way that you use `gen_rmq`?

**Comment by mkorszun** [comment]
I will close it once we have released the corresponding changes. I also recommend creating a dedicated feature request to support passing configuration via `start_link` function.

**Comment by spier** [comment]
@mkorszun I don't understand the "waiting for release" label on this issue. Is there already a PR that is associated with this?

**Comment by mkorszun** [comment]
@spier PR is merged already, but the new version has not been released yet.

**Comment by spier** [comment]
I see. Got confused there because I did not see a PR linked to this issue.
Thanks for the explanation!

**Comment by a3kov** [comment]
I found the PR in question
https://github.com/meltwater/gen_rmq/pull/152
It was about declaring init options, not about _passing_ them to the callback.
