### ISSUE TITLE
PRECONDITION_FAILED  :  inequivalent arg 'type' for exchange 'dok' in vhost 'hmasxyha': received 'topic' but current is 'direct'"}}, 

### ISSUE THREAD

**Issue by retf** [meltwater/gen_rmq#142]
Any idea about this error?

** (FunctionClauseError) no function clause matching in GenRMQ.Publisher.terminate/2
    (gen_rmq) lib/publisher.ex:299: GenRMQ.Publisher.terminate({{:shutdown, {:server_initiated_close, 406, "PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'dok' in vhost 'hmasxyha': received 'topic' but current is 'direct'"}}, {:gen_server, :call, [#PID<0.100.1>, {:call, {:"exchange.declare", 0, "dok", "topic", false, true, false, false, false, []}, :none, #PID<0.87.1>}, 60000]}},

**Comment by mkorszun** [comment]
@retf thanks for reporting. Will have a look and get back to you. Could you share details regarding your publisher setup, which might make it easier to investigate / debug?

**Comment by mkorszun** [comment]
@retf I have not started investigating it yet but it looks like the publisher tries to re-declare already existing exchange. By default, the publisher will declare `topic` exchange but it looks like it is already declared as `direct`. Could you confirm that? If you want to publish to a `direct` exchange type, you need to specify it in publisher config:
`exchange: {:direct, exchange_name}`

Still, we should handle it better and this will be the goal after we clarify it is the case.

**Comment by retf** [comment]
Yes, is that the problem! 

exchange: {:direct, "dok"}

this make it to work! tks

**Comment by mkorszun** [comment]
Thanks for the quick feedback. I will take this as an opportunity to improve error handling and documentation.

**Comment by retf** [comment]
Now I am testing consumer, and get:


** (FunctionClauseError) no function clause matching in GenRMQ.Consumer.terminate/2
    (gen_rmq) lib/consumer.ex:306: GenRMQ.Consumer.terminate({{:shutdown, {:server_initiated_close, 406, "PRECONDITION_FAILED - inequivalent arg 'x-dead-letter-exchange' for queue 'check_protocol' in vhost 'test': received the value 'dok.deadletter' of type 'longstr' but current is none"}}, {:gen_server, :call, [#PID<0.30002.0>, {:call, {:"queue.declare", 0, "check_protocol", false, true, false, false, false, [{"x-dead-letter-exchange", :longstr, "dok.deadletter"}]}, :none, #PID<0.29988.0>}, 60000]}}, %{config: [queue: %GenRMQ.Consumer.QueueConfiguration{durable: true, max_priority: nil, name: "check_protocol", ttl: nil}, exchange: {:direct, "dok"}, routing_key: "check_file_protocol", prefetch_count: "100", uri: "test", retry_delay_function: #Function<0.42070994/1 in Doktask.Task.Consumer.init/0>], module: Doktask.Task.Consumer, reconnect_attempt: 0})
    (stdlib) gen_server.erl:673: :gen_server.try_terminate/3
    (stdlib) gen_server.erl:858: :gen_server.terminate/10
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3

This is conf problem too?

**Comment by mkorszun** [comment]
@retf sounds like you already have `check_protocol` queue. Every consumer will set up a deadletter queue/exchange by default as well. This causes conflict. Try to disable deadletter setup by specifying in the config:

`deadletter: false`

If you have a custom dead-letter setup, you should also reflect it in the consumer setup by providing:

* `deadletter_queue` - defines the name of the deadletter queue (**Default:** Same as queue name suffixed by `_error`).

* `deadletter_exchange` - defines the name of the deadletter exchange (**Default:** Same as exchange name suffixed by `.deadletter`).

* `deadletter_routing_key` - defines the name of the deadletter routing key (**Default:** `#`).

**Comment by mkorszun** [comment]
@retf changes to improve the error handling are ready: https://github.com/meltwater/gen_rmq/pull/143

**Comment by mkorszun** [comment]
@retf Full consumer config documentation is here: https://hexdocs.pm/gen_rmq/GenRMQ.Consumer.html#c:init/0

**Comment by retf** [comment]
One more doubt, in consumer (init) I want pass a neme for connection, have any way to pass it. for sample in AMQP:

 AMQP.Connection.open(:util.to_binary(uri, @my_conn_name)

 thus I can see it on rabbit connection, like
18.229.160.240:39606
myrabbi_consumer_distribution | hmasxyha | running | ○ | AMQP 0-9-1 | 1 | 71B/s | 6.7kB/

**Comment by mkorszun** [comment]
@retf I believe it is not possible atm.

**Comment by vorce** [comment]
I think we can close this now. Thanks for the reports @retf 👍 

(Reopen if you feel differently @mkorszun)
