### ISSUE TITLE
How do i setup consumers for quorum queues

### ISSUE THREAD

**Issue by akashsethiya** [meltwater/gen_rmq#147]

**Comment by Shemeikka** [comment]
Hi,

Currently you can't give queue arguments to Consumer so this can't be done. The queue is always declared as classic type.

**Comment by akashsethiya** [comment]
Thanks for the reply

**Comment by Shemeikka** [comment]
I have worked on this and it's almost done. Requires new tests and documentation updates but otherwise it works.

I have added new option for the consumer init called 'queue_arguments' that accepts AMQP-library's [Queue.declare/3](https://hexdocs.pm/amqp/AMQP.Queue.html#declare/3) option's arguments. This works on my forked version.

Example on how it would work with quorum queue:
```
def init() do
    [
      queue: "example_queue",
      queue_arguments: [{"x-queue-type", :longstr ,"quorum"}]
      exchange: "example_exchange",
      routing_key: "routing_key.#",
      prefetch_count: "10",
      connection: "amqp://guest:guest@localhost:5672"
    ]
end
```

I think I can finish it on this weekend or next week and then create a pull request for it.

**Comment by akashsethiya** [comment]
@Shemeikka I was about to start work on this. Thanks 👍

**Comment by mkorszun** [comment]
@Shemeikka this is great. Looking forward for a PR.

**Comment by Shemeikka** [comment]
Well things changed a little.

There are now two new keys, queue_options and deadletter_queue_options, on init. These are queue options as declared in [AMQP.Queue.declare/3](https://hexdocs.pm/amqp/AMQP.Queue.html#declare/3). Both are optional.

All existing options like queue_ttl will still work but these new queue_options will be used if they are present.

Example
```elixir
def init() do
    [
      connection: "amqp://guest:guest@localhost:5672"
      queue: "example_queue",
      queue_options: [
        durable: true,
        arguments: [
          {"x-queue-type", :longstr ,"quorum"},
        ]
      deadletter_queue_options: [
        durable: false
        arguments: [
          {"x-expires :long, 10000},
        ]
      ],
      exchange: "example_exchange",
      routing_key: "routing_key.#",
      prefetch_count: "10",
    ]
end
```
Is this acceptable @mkorszun @vorce ?

**Comment by vorce** [comment]
@Shemeikka yes that looks good to me 👍

**Comment by spier** [comment]
@vorce looks like this feature was implemented in #150.  
Can this issue be closed?

**Comment by mkorszun** [comment]
I will close it once the corresponding changes are officially released.

**Comment by mkorszun** [comment]
@akashsethiya We can now support quorum queues. Please check our [dedicated guide for it](https://github.com/meltwater/gen_rmq/blob/master/documentation/guides/consumer/with_quorum_queue_type.md). In order to have this support, you need to use the latest version - 2.6.0
