### ISSUE TITLE
Trusted Committer Invitation: @vorce

### ISSUE THREAD

**Issue by spier** [meltwater/gen_rmq#165]
Hi @vorce ,

Thank you for your contributions to gen_rmq!

We want to see gen_rmq strive. To achieve that we are empowering more users to help us push the development of gen_rmq forward. For that purpose we are adding **Trusted Committers** to this repo.

Given your great contributions already, we want to **invite you to become a Trusted Committer of the gen_rmq project.** 🎉 

See details about the rights and expectations of a Trusted Committer in [TRUSTED-COMMITTERS.md](https://github.com/meltwater/gen_rmq/blob/master/TRUSTED-COMMITTERS.md).

Please let us know if you want to accept this invitation as a Trusted Committer, so that we can make the necessary changes in the repo permissions.

We hope you like the idea of the Trusted Committer concept, and would greatly appreciate any feedback and questions that you might  have about this.

Best
/Mateusz, Sebastian

**Comment by vorce** [comment]
I accept :) 🎉

**Comment by spier** [comment]
Awesome! Welcome and congratulations :)

We have already listed you [in here](https://github.com/meltwater/gen_rmq#trusted-committers) and are now hoping for some of the others that we invited to join us too so that we can push gen_rmq forward.

Will close this issue now.
