### ISSUE TITLE
Trusted Committer Invitation: @Shemeikka

### ISSUE THREAD

**Issue by spier** [meltwater/gen_rmq#166]
Hi @Shemeikka ,

Thank you for your contributions to gen_rmq!

We want to see gen_rmq strive. To achieve that we are empowering more users to help us push the development of gen_rmq forward. For that purpose we are adding **Trusted Committers** to this repo.

Given your great contributions already, we want to **invite you to become a Trusted Committer of the gen_rmq project.** 🎉 

See details about the rights and expectations of a Trusted Committer in [TRUSTED-COMMITTERS.md](https://github.com/meltwater/gen_rmq/blob/master/TRUSTED-COMMITTERS.md).

Please let us know if you want to accept this invitation as a Trusted Committer, so that we can make the necessary changes in the repo permissions.

We hope you like the idea of the Trusted Committer concept, and would greatly appreciate any feedback and questions that you might  have about this.

Best
/Mateusz, Joel, Sebastian

**Comment by Shemeikka** [comment]
I accept.

**Comment by spier** [comment]
That is great!
I will handle all required onboarding steps later today.

Would you also like us to announce you contributing to gen_rmq on our twitter channel? 
https://twitter.com/MeltwaterEng

If you would like this, please let me know if you have a twitter handle that I should mention. If no, no problem at all either. Just trying to make sure you are greeted with all appropriate honors :)

**Comment by Shemeikka** [comment]
No need to announce this.

**Comment by spier** [comment]
Alright, cool. Thanks for the quick feedback.

**Comment by spier** [comment]
@Shemeikka you should have received an invite now. Welcome on board as a Trusted Committer and we are looking forward to your contributions. Thanks for your help!

**Comment by spier** [comment]
A onboarding steps done. Closing this ticket.
