### ISSUE TITLE
Trusted Committer Invitation: @akoutmos

### ISSUE THREAD

**Issue by spier** [meltwater/gen_rmq#167]
Hi @akoutmos ,

Thank you for your contributions to gen_rmq!

We want to see gen_rmq strive. To achieve that we are empowering more users to help us push the development of gen_rmq forward. For that purpose we are adding **Trusted Committers** to this repo.

Given your great contributions already, we want to **invite you to become a Trusted Committer of the gen_rmq project.** 🎉 

See details about the rights and expectations of a Trusted Committer in [TRUSTED-COMMITTERS.md](https://github.com/meltwater/gen_rmq/blob/master/TRUSTED-COMMITTERS.md).

Please let us know if you want to accept this invitation as a Trusted Committer, so that we can make the necessary changes in the repo permissions.

We hope you like the idea of the Trusted Committer concept, and would greatly appreciate any feedback and questions that you might  have about this.

Best
/Mateusz, Joel, Sebastian

**Comment by spier** [comment]
Hi @akoutmos,  

just wanted to see if you have any questions about the above, and if you would like to support as gen_rmq as a Trusted Committer? We would love to have you on board.

Cheers
/Sebastian

**Comment by akoutmos** [comment]
Hey @spier and thanks for invitation! I genuinely appreciate it :).

Apologies on the delay...I must have missed the notification for this a week back. Crazy couple of weeks -_-. I would very much like to be a part of the gen_rmq team and to help out with the development+maintenance of the library. Let me know how you would like to proceed.

Take care!

**Comment by spier** [comment]
That is great!
I will handle all required onboarding steps later today.

Would you also like us to announce you contributing to gen_rmq on our twitter channel?
https://twitter.com/MeltwaterEng

If you would like this, please let me know if you have a twitter handle that I should mention. If no, no problem at all either. 

Just trying to make sure you are greeted with all appropriate honors :)

**Comment by spier** [comment]
@akoutmos you should have received an invite now. Welcome on board as a Trusted Committer and we are looking forward to your contributions. Thanks for your help!

**Comment by akoutmos** [comment]
Hey @spier! My twitter handle is also "akoutmos". I appreciate the warm welcome :)

**Comment by spier** [comment]
Boom! :) Welcome again. Closing this issue as all onboarding steps are done now.
https://twitter.com/MeltwaterEng/status/1250104786151714816

If you have any questions, feel free to reach out at any time.
