### ISSUE TITLE
Trusted Committer Invitation: @TreyE

### ISSUE THREAD

**Issue by spier** [meltwater/gen_rmq#168]
Hi @TreyE ,

Thank you for your contributions to gen_rmq!

We want to see gen_rmq strive. To achieve that we are empowering more users to help us push the development of gen_rmq forward. For that purpose we are adding **Trusted Committers** to this repo.

Given your great contributions already, we want to **invite you to become a Trusted Committer of the gen_rmq project.** 🎉 

See details about the rights and expectations of a Trusted Committer in [TRUSTED-COMMITTERS.md](https://github.com/meltwater/gen_rmq/blob/master/TRUSTED-COMMITTERS.md).

Please let us know if you want to accept this invitation as a Trusted Committer, so that we can make the necessary changes in the repo permissions.

We hope you like the idea of the Trusted Committer concept, and would greatly appreciate any feedback and questions that you might  have about this.

Best
/Mateusz, Joel, Sebastian

**Comment by TreyE** [comment]
I will take a look when I can, and thank.  Things are, understandably, a little nuts right now.

Thank you for the invite.

**Comment by spier** [comment]
Thanks for the quick reply @TreyE. 
We completely understand. Things are crazy everywhere right now.

If you have any questions about how this Trusted Committer concept is meant to work, please feel free to ask whatever is unclear.

Cheers

**Comment by spier** [comment]
Hi @TreyE, I suspect you got busy and don't have time right now?

I will close this ticket for the time being. If you ever get back to this and want to join us as a Trusted Committer for this project, just let us know and we can sort this out.

**Comment by TreyE** [comment]
Makes sense.
