### ISSUE TITLE
Question : How do I pause a queue and resume it letter

### ISSUE THREAD

**Issue by ehayun** [meltwater/gen_rmq#231]
I have a very large queue with a lot of messages to be process and it can take even days to complete them all.
I want to pause the queue during the night 
How do I do that

Thanks

**Comment by spier** [comment]
Hi @ehayun. Thanks for your message.

Can you maybe post some pseudo code or other information that would make it easier to understand how your current setup looks like and what you are trying to achieve?

From your questions I am not 100% sure if this is a question about `gen_rmq` or rather about `elixir` itself?

**Comment by ehayun** [comment]
It can be a question in gen_rmq or elixir. You are right
I actually solve it by supervising the gen_server that listen to the queue but I thought maybe you have a function that can do that without all the hassle

Thanks anyway
