### ISSUE TITLE
[FEATURE] AMQP lib version is outdated

### ISSUE THREAD

**Issue by williamweckl** [meltwater/gen_rmq#246]
Hi there, how are you guys? First of all thanks for the great work with this amazing library.

Is there a reason to AMQP library is still on version 1.1? Could be updated to 2.1?

**Additional context**

I'm migrating some publishers and consumers made by my own to use GenRMQ and today I'm using AMQP 2.1 version that for now is incompatible with GenRMQ. I can force to use the newer one, that I'm tending to do, but I'm not sure the impacts of doing this.

**Comment by williamweckl** [comment]
I see now that is a PR to update AMQP with some discussion on it: https://github.com/meltwater/gen_rmq/pull/235

I think this could be merged already.

**Comment by spier** [comment]
@vorce I see that the related PR #235 was closed. Also checking the code on master I see:
`{:amqp, "~> 3.0"}`

So just wanted to confirm with you if this issue here is resolved and can be closed?
(asking you as you reviewed that PR)

**Comment by vorce** [comment]
Yes we can close this, we upgraded amqp in https://github.com/meltwater/gen_rmq/pull/254 👍

**Comment by spier** [comment]
Perfect, thanks for the confirmation!
