### ISSUE TITLE
Publish new version to hex

### ISSUE THREAD

**Issue by tmartin8080** [meltwater/gen_rmq#255]
`3.0.0` on [hex.pm](https://hex.pm/packages/gen_rmq) still has `amqp` at `~> 1.1` but the [main branch](https://github.com/meltwater/gen_rmq/commit/ae6958c7f5d61b64e075020a9760cc5b64d749c3) has updated deps.  

<img width="593" alt="Screen Shot 2022-02-13 at 8 44 16 AM" src="https://user-images.githubusercontent.com/11931030/153756096-c0da5d2a-de99-4641-88a7-a903c5141788.png">

Can somebody publish a new version with the updated mix deps?

Currently using:

```elixir
{:gen_rmq, github: "meltwater/gen_rmq", commit: "ae6958c"},
```

**Comment by dynaum** [comment]
Please! 🙏

**Comment by spier** [comment]
Thanks for the report @tmartin8080 and confirmation @dynaum. Great to hear that you find this project useful 🥳
Out of curiosity, and as extra motivation for our team, can you share a bit about in which context you are using gen_rmq?

I will try out to reach to our internal team, to see who has time to work on this.

**Comment by mkorszun** [comment]
hey @dynaum, will do my best to release the new version by the end of this week.

**Comment by mkorszun** [comment]
hey @dynaum, will do my best to release the new version by the end of this week.

**Comment by mkorszun** [comment]
it is published

**Comment by spier** [comment]
@mkorszun should we also list the 4.0.0 version under the **Releases** section on GitHub?
