### ISSUE TITLE
Support to multiple routing keys

### ISSUE THREAD

**Issue by GabrielMalakias** [meltwater/gen_rmq#26]
Hello, 
First of all, thanks for open source this library! From my point of view it's the easiest to integrate to RabbitMQ that I found so far. 

I have just one question, here at company we have many projects using Ruby and almost all of them uses [Hutch](https://github.com/gocardless/hutch). I'm starting an Elixir project and I was looking for something as closer to Hutch as possible and then I've found this lib. This is a pretty cool project but I just miss one feature: Have the possibility to set multiple routing keys to a consumer. I'm just wondering, are you thinking about adding this feature in the future?

Currently I was trying to do something like this:

```elixir
defmodule Copan.Consumers.Appointment do
  @behaviour GenRMQ.Consumer
  def init() do
    [
      queue: "copan_appointment_created",
      exchange: "public",
      routing_key: ["appointments.v1.created", "appointments.v1.deleted"],
      uri: "amqp://guest:guest@localhost:5672",
      prefetch_count: "10",
      retry_delay_function: fn attempt -> :timer.sleep(2000 * attempt) end
    ]
  end
end
```
But It just throws this exception 

13:25:05.540 [error] CRASH REPORT Process <0.512.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size([<<"appointments.v1.created">>,<<"appointments.v1.deleted">>]) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
13:25:05.541 [error] Supervisor {<0.509.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.12531>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.511.0>, {<<"client 127.0.0.1:64132 -> 127.0.0.1:5672">>,1}) at <0.512.0> exit with reason bad argument in call to erlang:size([<<"appointments.v1.created">>,<<"appointments.v1.deleted">>]) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185 in context child_terminated
13:25:05.541 [error] Supervisor {<0.509.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.12531>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.511.0>, {<<"client 127.0.0.1:64132 -> 127.0.0.1:5672">>,1}) at <0.512.0> exit with reason reached_max_restart_intensity in context shutdown
** (EXIT from #PID<0.493.0>) shell process exited with reason: exited in: :gen_server.call(#PID<0.511.0>, {:call, {:"queue.bind", 0, "copan_appointment_created", "public", ["appointments.v1.created", "appointments.v1.deleted"], false, []}, :none, #PID<0.499.0>}, 60000)
    ** (EXIT) shutdown

**Comment by mkorszun** [comment]
@GabrielMalakias thanks for the issue. This is definitely something we will try to address soon. If you already have some ideas regarding the implementation feel free to propose a PR as well.

**Comment by mkorszun** [comment]
@GabrielMalakias couple of workaround ideas for your scenario:

1. Consumer binding/routing_key: `appointments.v1.*` will guarantee you will be getting messages with both keys
2. Start separate consumers for both types of messages

**Comment by vorce** [comment]
I will close this since there are good solutions for accomplishing the needed functionality.
