### ISSUE TITLE
Report metrics

### ISSUE THREAD

**Issue by mkorszun** [meltwater/gen_rmq#5]
I think you should be able to turn on metrics reporting. Default should probably be off(?).

Something like:
```
config :gen_amqp, :metrics,
  enabled: true, 
  host: "localhost",
  port: 8125,
  prefix: "myapp.amqp"
```

And then we can easily have some nice out-of-the box metrics for both consumers and publishers. 

Some stats that are probably interesting:
- Publish counts
- Consume count
- reject count (separate for with requeue?)
- ack count? (not sure about this one)
- timing for consumer

We most likely need to have some convention about adding consumer/publisher "name" to the metric path, so if you have several different consumers they report to different paths.

**Comment by vorce** [comment]
Adding [telemetry](https://github.com/beam-telemetry/telemetry) integration could be a solution to this.

**Comment by akoutmos** [comment]
@vorce Is adding telemetry to gen_rmq something you are working on? If not I would be very interested in picking this task up. Let me know. Thanks!

**Comment by mkorszun** [comment]
Hi @akoutmos, as far as I know, there is nothing in progress regarding telemetry integration. So go ahead with it. @vorce can always join you.

**Comment by akoutmos** [comment]
Sounds good! I'll get to work on something and open a PR when ready :). Thanks!

**Comment by vorce** [comment]
Yep, nothing started yet. So go for it @akoutmos !

**Comment by akoutmos** [comment]
Sounds good. I should have something up in the next few days :). Thanks!

**Comment by akoutmos** [comment]
@vorce @mkorszun I opened up PR #136 with my initial stab at integrating telemetry into gen_rmq. I will add tests and documentation once I get the green light that this is in line what you guys had in mind.

**Comment by mkorszun** [comment]
@akoutmos great, please continue on it. I have left some PR comments.

**Comment by akoutmos** [comment]
With #136 closed, this issue can probably be closed as well. I imagine that any future telemetry requests will be on a datapoint by datapoint basis. Thanks again for the speedy merge and excellent feedback!

**Comment by mkorszun** [comment]
Released 🎉

**Comment by akoutmos** [comment]
Awesome!!! Thanks a bunch for the release :)
