### ISSUE TITLE
Better caching for plt files on travis

### ISSUE THREAD

**Issue by mkorszun** [meltwater/gen_rmq#99]
Initial builds can take up to 15m. We should try to reduce it to 5m if possible.

**Comment by spier** [comment]
@mkorszun Given that it looks like you want to move to a different CI solution completely (see #100), shall we close this issue here?

**Comment by mkorszun** [comment]
Closing it for now. We should decide on the CI/CD solution -> https://github.com/meltwater/gen_rmq/issues/100
